plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
	id 'java'
}

group = 'com.chenweikeng.monkeycraft_api'
version = "1.0.0-mc${minecraft_version}"

repositories {
	mavenCentral()
	maven { url = "https://maven.fabricmc.net/" }
	maven { url = "https://maven.shedaniel.me/" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modCompileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	inputs.property "archivesName", "monkeycraft_api"

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = "monkeycraft-api"
			from components.java
		}
	}

	repositories {
		// Add repositories to publish to here.
	}
}
